"""create search_histories table

Revision ID: 46093a8f0d14
Revises: b6d8106ec9cf
Create Date: 2026-01-28 13:13:08.901189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46093a8f0d14'
down_revision: Union[str, Sequence[str], None] = 'b6d8106ec9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'search_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_histories_id'), 'search_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_histories_id'), table_name='search_histories')
    op.drop_index('idx_user_created', table_name='search_histories')
    op.drop_table('search_histories')
    # ### end Alembic commands ###
